import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.css';
import './globals.css';
import TodoList from './components/TodoList';

// Initialize the Inter font
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Page = () => (
  <html lang="en">
    <body className={inter.className}>
      <TodoList />
    </body>
  </html>
);

export default Page;
