export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true}>
                {children}
            </body>
        </html>
    );
};

export default RootLayout;